/**
 * Challenges: standalone CODING problems, grouped by difficulty, separate from
 * the quiz at the end of each lesson.
 *
 * A lesson's quiz checks whether someone read that lesson. A challenge asks
 * them to actually write working code -- a function stub, and hidden test
 * cases that decide whether it is right. Nothing is gated on them; they are
 * practice, which is also why they award no XP (that comes from lessons).
 *
 * Every problem here is deliberately answerable from what the five written
 * Physical AI lessons teach, plus ordinary beginner Python. A challenge that
 * needs knowledge the platform never taught is not a challenge, it is a
 * gotcha.
 *
 * REPO-LEVEL FALLBACK, same as lesson-bodies.ts and lesson-quizzes.ts: works
 * with zero Firestore setup, and is what importStarterContent seeds.
 *
 * On test design: `call` and `expected` are Python expressions, evaluated and
 * compared, so lists and strings compare properly. Some cases are visible as
 * worked examples; the rest are hidden, so the answer cannot be reverse
 * engineered from the examples alone.
 */
import type { ChallengeDoc } from "./schema";

export const repoChallenges: Record<string, ChallengeDoc[]> = {
  "physical-ai": [
    {
      id: "ph-c-steer",
      order: 0,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "Which way to turn" },
      prompt: { en: "The camera finds an object and reports its horizontal pixel position `x` in an image `width` pixels wide. Split the view into three equal bands: if the object is in the left third return \"left\", in the right third return \"right\", otherwise it is roughly ahead so return \"forward\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def steer(x, width):\n    # Left third -> \"left\", right third -> \"right\", middle -> \"forward\"\n    pass\n",
      tests: [
        { call: "steer(10, 300)", expected: "\"left\"" },
        { call: "steer(150, 300)", expected: "\"forward\"" },
        { call: "steer(290, 300)", expected: "\"right\"" },
        { call: "steer(100, 300)", expected: "\"forward\"", hidden: true },
        { call: "steer(99, 300)", expected: "\"left\"", hidden: true },
      ],
      tutorial: { en: "The two boundaries are at width/3 and 2*width/3. Everything below the first is left, everything above the second is right, and whatever is left over is forward.\n\nWrite it as two checks and a fallback -- if it is not left and not right, it must be forward, so you do not need a third comparison.\n\nMind the edges: a pixel sitting exactly ON width/3 is not in the left third any more, so use a strict `<` for that test." },
      editorial: { en: "    def steer(x, width):\n        if x < width / 3:\n            return \"left\"\n        if x > 2 * width / 3:\n            return \"right\"\n        return \"forward\"\n\nNo `else` needed. Each `return` exits the function immediately, so reaching the last line already means both earlier checks failed.\n\nThe hidden tests target exactly the boundary: 100 out of 300 is width/3 precisely, and `100 < 100` is False, so it is forward -- while 99 is genuinely inside the left band. Off-by-one at a boundary is the single most common bug in this kind of banding, which is why it is tested rather than assumed." },
      explanation: { en: "This is the last step of the vision pipeline from the lesson: the camera gives a pixel, and the robot has to turn that into a decision. Nothing here knows what the object IS -- only where it sits in frame, which is often all a robot needs to start moving toward it." },
    },
    {
      id: "ph-c-power",
      order: 1,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "Battery supervisor" },
      prompt: { en: "A robot must change behaviour as its battery drains. Above 50 percent it runs normally. Above 20 it should conserve power. At 20 or below it must head back to the charger. Return \"normal\", \"saving\" or \"return_home\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def power_mode(battery_pct):\n    # >50 -> \"normal\",  >20 -> \"saving\",  otherwise -> \"return_home\"\n    pass\n",
      tests: [
        { call: "power_mode(80)", expected: "\"normal\"" },
        { call: "power_mode(35)", expected: "\"saving\"" },
        { call: "power_mode(10)", expected: "\"return_home\"" },
        { call: "power_mode(50)", expected: "\"saving\"", hidden: true },
        { call: "power_mode(20)", expected: "\"return_home\"", hidden: true },
      ],
      tutorial: { en: "Three outcomes, so two comparisons and a fallback.\n\nOrder matters: check the highest threshold first. If you test `> 20` before `> 50`, then 80 matches the first test and you return \"saving\" for a full battery.\n\nRead the boundaries carefully. \"Above 50\" means 50 itself is NOT normal, and \"at 20 or below\" means 20 is already return_home. Both are tested." },
      editorial: { en: "    def power_mode(battery_pct):\n        if battery_pct > 50:\n            return \"normal\"\n        if battery_pct > 20:\n            return \"saving\"\n        return \"return_home\"\n\nHighest threshold first is what makes the chain work: by the time the second line runs, the value is already known to be 50 or less, so `> 20` really means \"between 21 and 50\".\n\nBoth hidden tests sit exactly on a boundary, because \"above 50\" and \"50 or more\" are one character apart in code and completely different in behaviour -- and a robot that thinks a 20 percent battery is fine is a robot you go and fetch from under a table." },
      explanation: { en: "Behaviour that changes with battery level is in every real robot. The thresholds are a policy decision, but the shape -- ordered checks, most urgent last -- is always this." },
    },
    {
      id: "ph-c-step",
      order: 2,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Move a joint safely" },
      prompt: { en: "A servo cannot jump to a new angle instantly; it moves a little each control tick. Write `step_toward` that returns the joint's next angle: move from `current` toward `target` by at most `max_step` degrees. If the target is already within reach, return the target exactly rather than overshooting." },
      options: [],
      correctIndex: 0,
      starterCode: "def step_toward(current, target, max_step):\n    # Move at most max_step degrees toward target, never past it.\n    pass\n",
      tests: [
        { call: "step_toward(0, 90, 10)", expected: "10" },
        { call: "step_toward(85, 90, 10)", expected: "90" },
        { call: "step_toward(90, 0, 10)", expected: "80" },
        { call: "step_toward(5, 0, 10)", expected: "0", hidden: true },
        { call: "step_toward(45, 45, 10)", expected: "45", hidden: true },
      ],
      tutorial: { en: "Work out the distance left to travel first: `target - current`. Its SIGN tells you which way to move, and its size tells you whether one step is enough.\n\nIf the remaining distance is no bigger than max_step, you can finish this tick -- return target. Otherwise move exactly max_step in the right direction.\n\n`abs()` gives you the size without the sign, which is what the \"is it close enough\" test needs." },
      editorial: { en: "    def step_toward(current, target, max_step):\n        remaining = target - current\n        if abs(remaining) <= max_step:\n            return target\n        if remaining > 0:\n            return current + max_step\n        return current - max_step\n\nReturning `target` instead of `current + remaining` matters: they are equal in value, but returning the target says what you mean, and it can never drift by a floating-point hair.\n\nThe \"already there\" case (45 to 45) falls out for free -- remaining is 0, `abs(0) <= max_step` is true, and you return 45 without a special branch.\n\nThis is rate limiting, and it is why a real arm moves smoothly instead of slamming to position: the control loop calls this every tick with the same target until it arrives." },
      explanation: { en: "This is the gap between commanded and actual position from the actuators lesson, handled deliberately. The controller never asks for a jump it cannot make -- it asks for the next small step, over and over." },
    },
    {
      id: "ph-c-fuse",
      order: 3,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Trust the right sensor" },
      prompt: { en: "The camera estimates distance and so does the LiDAR, and they rarely agree exactly. If they differ by more than 20 percent of the LiDAR reading, the camera is probably wrong -- trust the LiDAR alone. Otherwise average the two. Always return a float rounded to 1 decimal place." },
      options: [],
      correctIndex: 0,
      starterCode: "def fuse(camera_cm, lidar_cm):\n    # Disagree by more than 20% of lidar -> trust lidar.\n    # Otherwise return their average, rounded to 1 decimal.\n    pass\n",
      tests: [
        { call: "fuse(100, 100)", expected: "100.0" },
        { call: "fuse(50, 100)", expected: "100.0" },
        { call: "fuse(102, 100)", expected: "101.0" },
        { call: "fuse(0, 10)", expected: "10.0", hidden: true },
        { call: "fuse(9, 10)", expected: "9.5", hidden: true },
      ],
      tutorial: { en: "Two steps. First measure the disagreement: `abs(camera_cm - lidar_cm)`. Then compare it against 20 percent of the lidar reading, which is `0.2 * lidar_cm`.\n\nIf it is bigger, return the lidar value -- but as a float, so use `float(...)` or round it, otherwise 100 comes back as an int and will not match 100.0.\n\nIf it is not bigger, average them and `round(value, 1)`." },
      editorial: { en: "    def fuse(camera_cm, lidar_cm):\n        if abs(camera_cm - lidar_cm) > 0.2 * lidar_cm:\n            return float(lidar_cm)\n        return round((camera_cm + lidar_cm) / 2, 1)\n\nThe threshold is RELATIVE, not absolute, and that is the interesting part. A 10cm disagreement is nothing at 5 metres and enormous at 20cm, so the tolerance scales with the reading -- which is why it is `0.2 * lidar_cm` rather than a fixed number.\n\n`float(lidar_cm)` is not fussiness: the tests compare against 100.0, and while `100 == 100.0` is True in Python, being deliberate about the return type keeps this function's contract honest -- it always returns a float.\n\nfuse(0, 10) is the camera failing completely; the disagreement is 10, well over 2, so the lidar wins." },
      explanation: { en: "This is sensor fusion from the lesson, made concrete: no single sensor is trusted blindly, and the rule for when to distrust one is itself part of the robot's design." },
    },
    {
      id: "ph-c-plan",
      order: 4,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "Plan the collection order" },
      prompt: { en: "The camera returns detected objects as (colour, distance) pairs. The robot only has bins for red and green -- anything else must be ignored entirely. Return the list of COLLECTABLE colours in the order the robot should visit them: nearest first." },
      options: [],
      correctIndex: 0,
      starterCode: "def plan(objects):\n    # objects: [(\"red\", 2.0), (\"blue\", 1.0)]\n    # Only \"red\" and \"green\" are collectable. Nearest first.\n    pass\n",
      tests: [
        { call: "plan([(\"blue\", 1.0), (\"red\", 2.0), (\"green\", 0.5)])", expected: "[\"green\", \"red\"]" },
        { call: "plan([])", expected: "[]" },
        { call: "plan([(\"blue\", 1.0)])", expected: "[]", hidden: true },
        { call: "plan([(\"red\", 3.0), (\"green\", 1.0), (\"red\", 2.0)])", expected: "[\"green\", \"red\", \"red\"]", hidden: true },
      ],
      tutorial: { en: "Two operations in order: filter, then sort.\n\nFirst keep only the pairs whose colour is collectable -- `if colour in (\"red\", \"green\")`. Then sort what survives by distance, which is index 1 of each pair, using `sorted(..., key=...)`.\n\nFinally return just the colours, not the pairs -- so pull index 0 out of each after sorting.\n\nFilter before you sort. Sorting things you are about to throw away is wasted work, and it keeps the two steps separate in your head." },
      editorial: { en: "    COLLECTABLE = (\"red\", \"green\")\n\n    def plan(objects):\n        wanted = [o for o in objects if o[0] in COLLECTABLE]\n        wanted.sort(key=lambda o: o[1])\n        return [colour for colour, _ in wanted]\n\nThree lines, one job each: filter, sort, extract.\n\n`key=lambda o: o[1]` sorts by distance. Without the key, Python would sort the tuples themselves -- which compares the COLOUR first, and you would get alphabetical order with distance as a tiebreak. Silently wrong, and the first test would catch it only because green happens to also be nearest.\n\n`for colour, _ in wanted` unpacks each pair and uses `_` for the distance, the conventional name for a value you are deliberately ignoring.\n\nDuplicates work without any special handling -- two reds stay two reds, correctly ordered between the greens." },
      explanation: { en: "This is the whole waste-sorting mission in miniature: see everything, discard what you cannot handle, and do the rest in a sensible order. Deciding what to IGNORE is as much a part of the plan as deciding what to do." },
    },
    {
      id: "ph-c-mission",
      order: 5,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "A loop that remembers" },
      prompt: { en: "Now the control loop needs memory. Walk through the distance readings in order and return one action per reading:\n\n- Under 20: the way is blocked, so \"stop\".\n- Otherwise, if the PREVIOUS action was \"stop\", the robot is stopped and must \"turn\" before it can move again.\n- Otherwise \"go\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def mission(readings):\n    # under 20 -> \"stop\"\n    # previous action was \"stop\" -> \"turn\"\n    # otherwise -> \"go\"\n    pass\n",
      tests: [
        { call: "mission([100, 10, 100, 100])", expected: "[\"go\", \"stop\", \"turn\", \"go\"]" },
        { call: "mission([])", expected: "[]" },
        { call: "mission([10, 10])", expected: "[\"stop\", \"stop\"]", hidden: true },
        { call: "mission([50])", expected: "[\"go\"]", hidden: true },
        { call: "mission([10, 100, 10])", expected: "[\"stop\", \"turn\", \"stop\"]", hidden: true },
      ],
      tutorial: { en: "The difference from an ordinary loop is that this decision depends on the PREVIOUS one, so you have to remember it.\n\nKeep a variable holding the last action, starting as something that is not \"stop\" (there was no previous action on the first reading, and the robot is not stopped before it begins).\n\nInside the loop: decide, append, and then update that variable before moving on. The order matters -- update it AFTER you have used it for this tick.\n\nCheck \"blocked\" first: a reading under 20 is stop no matter what came before." },
      editorial: { en: "    def mission(readings):\n        actions = []\n        previous = None\n        for reading in readings:\n            if reading < 20:\n                action = \"stop\"\n            elif previous == \"stop\":\n                action = \"turn\"\n            else:\n                action = \"go\"\n            actions.append(action)\n            previous = action\n        return actions\n\nDeciding into a variable, then appending, then updating `previous` keeps the three concerns from tangling. Appending directly inside each branch works too, but then you need `previous = actions[-1]` afterwards, which is easy to forget.\n\n[10, 10] gives [\"stop\", \"stop\"], not [\"stop\", \"turn\"] -- because still being blocked outranks having just stopped. That is the ordering of the checks doing real work, and it is the behaviour you want: a robot that turns into a wall because it turned on a schedule rather than on what it can see is a broken robot.\n\nThis is a state machine, the smallest useful one. `previous` IS the state." },
      explanation: { en: "Every non-trivial robot behaviour needs memory of what it just did -- you cannot decide whether to turn without knowing you already stopped. This is where the sense-think-act loop stops being a filter over readings and starts being a controller." },
    },
  ],

  "python-primer": [
    {
      id: "pp-c-1-easy",
      lessonId: "pp-1",
      order: 0,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "Say hello", fr: "Dire bonjour" },
      prompt: { en: "Write a function `hello` that RETURNS the text \"Hello!\". Notice: return it, do not print it.", fr: "\u00c9cris une fonction `hello` qui RENVOIE le texte \"Hello!\". Attention : renvoie-le, ne l'affiche pas." },
      options: [],
      correctIndex: 0,
      starterCode: "def hello():\n    # Return the text, do not print it.\n    pass\n",
      tests: [
        { call: "hello()", expected: "\"Hello!\"" },
      ],
      tutorial: { en: "`return` hands a value back. `print` only shows it on screen and hands back nothing, so the test would see None." },
      editorial: { en: "    def hello():\n        return \"Hello!\"\n\nThat is the whole thing. The quotes matter -- without them Python goes looking for something named Hello." },
      explanation: { en: "Every challenge here checks what your function RETURNS. Getting that straight now saves a lot of confusion later." },
    },
    {
      id: "pp-c-1-medium",
      lessonId: "pp-1",
      order: 1,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Shout it", fr: "Crie-le" },
      prompt: { en: "Write `shout` that takes a word and RETURNS it with an exclamation mark on the end. shout(\"stop\") gives \"stop!\".", fr: "\u00c9cris `shout` qui prend un mot et le RENVOIE avec un point d'exclamation \u00e0 la fin. shout(\"stop\") donne \"stop!\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def shout(word):\n    pass\n",
      tests: [
        { call: "shout(\"stop\")", expected: "\"stop!\"" },
        { call: "shout(\"go\")", expected: "\"go!\"" },
        { call: "shout(\"\")", expected: "\"!\"", hidden: true },
      ],
      tutorial: { en: "Adding two pieces of text glues them together: \"a\" + \"b\" is \"ab\"." },
      editorial: { en: "    def shout(word):\n        return word + \"!\"" },
      explanation: { en: "Joining text with + is the simplest thing you can do with strings, and you will do it constantly." },
    },
    {
      id: "pp-c-1-hard",
      lessonId: "pp-1",
      order: 2,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "Three lines", fr: "Trois lignes" },
      prompt: { en: "Write `three_lines` that RETURNS the text \"one\\ntwo\\nthree\". The \\n is a new line -- one line for each word.", fr: "\u00c9cris `three_lines` qui RENVOIE le texte \"one\\ntwo\\nthree\". Le \\n est un retour \u00e0 la ligne -- une ligne par mot." },
      options: [],
      correctIndex: 0,
      starterCode: "def three_lines():\n    pass\n",
      tests: [
        { call: "three_lines()", expected: "\"one\\ntwo\\nthree\"" },
      ],
      tutorial: { en: "You can put \\n inside a string and it becomes a line break. Joining three pieces with + works too." },
      editorial: { en: "    def three_lines():\n        return \"one\\ntwo\\nthree\"\n\nThe \\n is one character, not two, even though you type two." },
      explanation: { en: "print() adds a line break for you at the end. Inside a string, you ask for one yourself with \\n." },
    },
    {
      id: "pp-c-2-easy",
      lessonId: "pp-2",
      order: 3,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "Double it", fr: "Le double" },
      prompt: { en: "Write `double` that takes a number and RETURNS it multiplied by two.", fr: "\u00c9cris `double` qui prend un nombre et RENVOIE son double." },
      options: [],
      correctIndex: 0,
      starterCode: "def double(n):\n    pass\n",
      tests: [
        { call: "double(4)", expected: "8" },
        { call: "double(0)", expected: "0" },
        { call: "double(-3)", expected: "-6", hidden: true },
      ],
      tutorial: { en: "`*` multiplies. The answer goes back with `return`." },
      editorial: { en: "    def double(n):\n        return n * 2" },
      explanation: { en: "Something in, something out. That is the shape of nearly every function you will write." },
    },
    {
      id: "pp-c-2-medium",
      lessonId: "pp-2",
      order: 4,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Describe the robot", fr: "D\u00e9cris le robot" },
      prompt: { en: "Write `describe` that takes a name and a number of legs, and RETURNS a sentence like \"Axi has 4 legs.\"", fr: "\u00c9cris `describe` qui prend un nom et un nombre de pattes, et RENVOIE une phrase comme \"Axi has 4 legs.\"" },
      options: [],
      correctIndex: 0,
      starterCode: "def describe(name, legs):\n    pass\n",
      tests: [
        { call: "describe(\"Axi\", 4)", expected: "\"Axi has 4 legs.\"" },
        { call: "describe(\"Robo\", 2)", expected: "\"Robo has 2 legs.\"" },
        { call: "describe(\"X\", 0)", expected: "\"X has 0 legs.\"", hidden: true },
      ],
      tutorial: { en: "An f-string drops a variable straight into text: f\"{name} has {legs} legs.\"" },
      editorial: { en: "    def describe(name, legs):\n        return f\"{name} has {legs} legs.\"\n\nWithout an f-string you would need str(legs), because you cannot add a number to text." },
      explanation: { en: "f-strings are how you build a sentence out of pieces without a pile of + signs." },
    },
    {
      id: "pp-c-2-hard",
      lessonId: "pp-2",
      order: 5,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "Text into numbers", fr: "Du texte en nombres" },
      prompt: { en: "Write `add_texts` that takes TWO pieces of text, each holding a number, and RETURNS their real total as a number. add_texts(\"3\", \"5\") gives 8, not \"35\".", fr: "\u00c9cris `add_texts` qui prend DEUX textes contenant chacun un nombre, et RENVOIE leur vrai total en nombre. add_texts(\"3\", \"5\") donne 8, pas \"35\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def add_texts(a, b):\n    pass\n",
      tests: [
        { call: "add_texts(\"3\", \"5\")", expected: "8" },
        { call: "add_texts(\"10\", \"1\")", expected: "11" },
        { call: "add_texts(\"0\", \"0\")", expected: "0", hidden: true },
      ],
      tutorial: { en: "`int(\"3\")` turns text into the number 3. Do that to both before adding." },
      editorial: { en: "    def add_texts(a, b):\n        return int(a) + int(b)\n\nWithout int(), + glues the text together: \"3\" + \"5\" is \"35\"." },
      explanation: { en: "Data arriving from outside your program is almost always text. Turning it into numbers is a daily job." },
    },
    {
      id: "pp-c-3-easy",
      lessonId: "pp-3",
      order: 6,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "Too close?", fr: "Trop pr\u00e8s ?" },
      prompt: { en: "Write `is_close` that takes a distance in cm and RETURNS True when it is under 20, otherwise False.", fr: "\u00c9cris `is_close` qui prend une distance en cm et RENVOIE True si elle est sous 20, sinon False." },
      options: [],
      correctIndex: 0,
      starterCode: "def is_close(distance):\n    pass\n",
      tests: [
        { call: "is_close(15)", expected: "True" },
        { call: "is_close(30)", expected: "False" },
        { call: "is_close(20)", expected: "False", hidden: true },
      ],
      tutorial: { en: "`distance < 20` is already True or False. You can return it directly." },
      editorial: { en: "    def is_close(distance):\n        return distance < 20\n\nThe long way works too:\n\n    if distance < 20:\n        return True\n    else:\n        return False\n\nBoth are correct. The first says the same thing in one line." },
      explanation: { en: "A comparison IS a True/False value. You do not need an if to make one." },
    },
    {
      id: "pp-c-3-medium",
      lessonId: "pp-3",
      order: 7,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Power mode", fr: "Mode d'\u00e9nergie" },
      prompt: { en: "Write `power_mode` that takes a battery percentage and RETURNS \"normal\" above 50, \"saving\" above 20, and \"home\" otherwise. Exactly 50 is saving; exactly 20 is home.", fr: "\u00c9cris `power_mode` qui prend un pourcentage de batterie et RENVOIE \"normal\" au-dessus de 50, \"saving\" au-dessus de 20, et \"home\" sinon. Exactement 50 c'est saving ; exactement 20 c'est home." },
      options: [],
      correctIndex: 0,
      starterCode: "def power_mode(battery):\n    pass\n",
      tests: [
        { call: "power_mode(80)", expected: "\"normal\"" },
        { call: "power_mode(35)", expected: "\"saving\"" },
        { call: "power_mode(5)", expected: "\"home\"" },
        { call: "power_mode(50)", expected: "\"saving\"", hidden: true },
        { call: "power_mode(20)", expected: "\"home\"", hidden: true },
      ],
      tutorial: { en: "Use if / elif / else and check the biggest number first. Read the boundaries carefully: \"above 50\" means > 50, not >= 50." },
      editorial: { en: "    def power_mode(battery):\n        if battery > 50:\n            return \"normal\"\n        elif battery > 20:\n            return \"saving\"\n        else:\n            return \"home\"\n\nOrder matters. If you tested > 20 first, a battery of 80 would answer \"saving\" and stop there." },
      explanation: { en: "Getting boundaries right is most of the work in real code. The hidden tests are exactly the boundaries." },
    },
    {
      id: "pp-c-3-hard",
      lessonId: "pp-3",
      order: 8,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "Safe to move", fr: "On peut avancer" },
      prompt: { en: "Write `can_move` that takes battery and distance, and RETURNS True only when the battery is above 20 AND the distance is above 10.", fr: "\u00c9cris `can_move` qui prend batterie et distance, et RENVOIE True seulement si la batterie d\u00e9passe 20 ET la distance d\u00e9passe 10." },
      options: [],
      correctIndex: 0,
      starterCode: "def can_move(battery, distance):\n    pass\n",
      tests: [
        { call: "can_move(60, 30)", expected: "True" },
        { call: "can_move(10, 30)", expected: "False" },
        { call: "can_move(60, 5)", expected: "False" },
        { call: "can_move(20, 11)", expected: "False", hidden: true },
        { call: "can_move(21, 11)", expected: "True", hidden: true },
      ],
      tutorial: { en: "`and` needs both sides to be true. You can return the whole comparison in one line." },
      editorial: { en: "    def can_move(battery, distance):\n        return battery > 20 and distance > 10\n\nThe hidden tests sit right on the boundary: 20 is not above 20." },
      explanation: { en: "Two conditions joined by `and` is how nearly every safety check in robotics is written." },
    },
    {
      id: "pp-c-4-easy",
      lessonId: "pp-4",
      order: 9,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "Add them up", fr: "Fais la somme" },
      prompt: { en: "Write `total` that takes a whole number n and RETURNS 1 + 2 + ... + n. total(4) gives 10.", fr: "\u00c9cris `total` qui prend un entier n et RENVOIE 1 + 2 + ... + n. total(4) donne 10." },
      options: [],
      correctIndex: 0,
      starterCode: "def total(n):\n    result = 0\n    # Loop from 1 to n and add each one to result.\n    return result\n",
      tests: [
        { call: "total(4)", expected: "10" },
        { call: "total(1)", expected: "1" },
        { call: "total(0)", expected: "0", hidden: true },
      ],
      tutorial: { en: "`for i in range(1, n + 1)` walks 1 up to n. Add each i onto result." },
      editorial: { en: "    def total(n):\n        result = 0\n        for i in range(1, n + 1):\n            result = result + i\n        return result\n\nrange(1, n + 1) stops BEFORE n + 1, which means it ends at n." },
      explanation: { en: "Start at zero, add inside the loop, return at the end. This pattern turns up everywhere." },
    },
    {
      id: "pp-c-4-medium",
      lessonId: "pp-4",
      order: 10,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Countdown", fr: "Compte \u00e0 rebours" },
      prompt: { en: "Write `countdown` that takes n and RETURNS a list counting down from n to 1. countdown(3) gives [3, 2, 1].", fr: "\u00c9cris `countdown` qui prend n et RENVOIE une liste de n jusqu'\u00e0 1. countdown(3) donne [3, 2, 1]." },
      options: [],
      correctIndex: 0,
      starterCode: "def countdown(n):\n    out = []\n    # Add each number to out, biggest first.\n    return out\n",
      tests: [
        { call: "countdown(3)", expected: "[3, 2, 1]" },
        { call: "countdown(1)", expected: "[1]" },
        { call: "countdown(0)", expected: "[]", hidden: true },
      ],
      tutorial: { en: "A while loop fits well: keep going while n is above 0, adding n and then making it one smaller." },
      editorial: { en: "    def countdown(n):\n        out = []\n        while n > 0:\n            out.append(n)\n            n = n - 1\n        return out\n\nForgetting `n = n - 1` gives a loop that never ends. The page stops it for you after a few seconds." },
      explanation: { en: "Every while loop needs something inside it that eventually makes the condition false." },
    },
    {
      id: "pp-c-4-hard",
      lessonId: "pp-4",
      order: 11,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "First one over", fr: "Le premier au-dessus" },
      prompt: { en: "Write `first_over` that takes a list of numbers and a limit, and RETURNS the FIRST number bigger than the limit. If there is none, return None.", fr: "\u00c9cris `first_over` qui prend une liste de nombres et une limite, et RENVOIE le PREMIER nombre plus grand que la limite. S'il n'y en a pas, renvoie None." },
      options: [],
      correctIndex: 0,
      starterCode: "def first_over(numbers, limit):\n    pass\n",
      tests: [
        { call: "first_over([3, 12, 40], 10)", expected: "12" },
        { call: "first_over([1, 2], 10)", expected: "None" },
        { call: "first_over([50, 12], 10)", expected: "50" },
        { call: "first_over([], 5)", expected: "None", hidden: true },
      ],
      tutorial: { en: "Walk the list with a for loop. The moment you find one, return it -- returning leaves the function immediately." },
      editorial: { en: "    def first_over(numbers, limit):\n        for n in numbers:\n            if n > limit:\n                return n\n        return None\n\nThe last line only runs if the loop finished without returning, which means nothing matched." },
      explanation: { en: "Returning from inside a loop is how you stop early, and it is cleaner than break plus an extra variable." },
    },
    {
      id: "pp-c-5-easy",
      lessonId: "pp-5",
      order: 12,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "Area", fr: "L'aire" },
      prompt: { en: "Write `area` that takes a width and a height and RETURNS the area of the rectangle.", fr: "\u00c9cris `area` qui prend une largeur et une hauteur et RENVOIE l'aire du rectangle." },
      options: [],
      correctIndex: 0,
      starterCode: "def area(width, height):\n    pass\n",
      tests: [
        { call: "area(3, 4)", expected: "12" },
        { call: "area(10, 2)", expected: "20" },
        { call: "area(0, 5)", expected: "0", hidden: true },
      ],
      tutorial: { en: "Width times height. `*` multiplies." },
      editorial: { en: "    def area(width, height):\n        return width * height" },
      explanation: { en: "Two arguments in, one answer out. Naming them width and height makes the function explain itself." },
    },
    {
      id: "pp-c-5-medium",
      lessonId: "pp-5",
      order: 13,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "A greeting you can change", fr: "Une salutation modifiable" },
      prompt: { en: "Write `greet` that takes a name and an OPTIONAL greeting defaulting to \"Hello\", and RETURNS \"Hello, Sara!\" or \"Hi, Sara!\" depending on what was passed.", fr: "\u00c9cris `greet` qui prend un nom et une salutation OPTIONNELLE valant \"Hello\" par d\u00e9faut, et RENVOIE \"Hello, Sara!\" ou \"Hi, Sara!\" selon ce qui est pass\u00e9." },
      options: [],
      correctIndex: 0,
      starterCode: "def greet(name, greeting=\"Hello\"):\n    pass\n",
      tests: [
        { call: "greet(\"Sara\")", expected: "\"Hello, Sara!\"" },
        { call: "greet(\"Sara\", \"Hi\")", expected: "\"Hi, Sara!\"" },
        { call: "greet(\"\", \"Yo\")", expected: "\"Yo, !\"", hidden: true },
      ],
      tutorial: { en: "The default is already written for you in the stub. Just build the sentence with an f-string." },
      editorial: { en: "    def greet(name, greeting=\"Hello\"):\n        return f\"{greeting}, {name}!\"\n\nA default value makes an argument optional. Callers who do not care get the sensible answer." },
      explanation: { en: "Default arguments let one function serve the simple case and the flexible case at once." },
    },
    {
      id: "pp-c-5-hard",
      lessonId: "pp-5",
      order: 14,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "Divide safely", fr: "Diviser sans planter" },
      prompt: { en: "Write `safe_divide` that RETURNS a divided by b, but RETURNS 0 when b is 0 -- instead of crashing.", fr: "\u00c9cris `safe_divide` qui RENVOIE a divis\u00e9 par b, mais RENVOIE 0 quand b vaut 0 -- au lieu de planter." },
      options: [],
      correctIndex: 0,
      starterCode: "def safe_divide(a, b):\n    pass\n",
      tests: [
        { call: "safe_divide(10, 2)", expected: "5" },
        { call: "safe_divide(9, 0)", expected: "0" },
        { call: "safe_divide(0, 4)", expected: "0" },
        { call: "safe_divide(7, 2)", expected: "3.5", hidden: true },
      ],
      tutorial: { en: "Check for the bad case first and return early. Everything after that can assume b is safe." },
      editorial: { en: "    def safe_divide(a, b):\n        if b == 0:\n            return 0\n        return a / b\n\nHandling the bad case first is called a guard. It keeps the normal path clean." },
      explanation: { en: "Dividing by zero crashes Python. Guarding against it is a habit worth building now." },
    },
    {
      id: "pp-c-6-easy",
      lessonId: "pp-6",
      order: 15,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "First letter", fr: "La premi\u00e8re lettre" },
      prompt: { en: "Write `initial` that takes a name and RETURNS its first letter as a capital. initial(\"sara\") gives \"S\".", fr: "\u00c9cris `initial` qui prend un nom et RENVOIE sa premi\u00e8re lettre en majuscule. initial(\"sara\") donne \"S\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def initial(name):\n    pass\n",
      tests: [
        { call: "initial(\"sara\")", expected: "\"S\"" },
        { call: "initial(\"Axi\")", expected: "\"A\"" },
        { call: "initial(\"z\")", expected: "\"Z\"", hidden: true },
      ],
      tutorial: { en: "`name[0]` is the first character. `.upper()` makes it a capital." },
      editorial: { en: "    def initial(name):\n        return name[0].upper()\n\nPositions start at 0, so [0] really is the first one." },
      explanation: { en: "Counting characters from zero feels wrong for about a week, then feels normal for ever." },
    },
    {
      id: "pp-c-6-medium",
      lessonId: "pp-6",
      order: 16,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Initials", fr: "Les initiales" },
      prompt: { en: "Write `initials` that takes a full name and RETURNS the initials joined by dots. initials(\"ada lovelace\") gives \"A.L\".", fr: "\u00c9cris `initials` qui prend un nom complet et RENVOIE les initiales s\u00e9par\u00e9es par des points. initials(\"ada lovelace\") donne \"A.L\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def initials(full_name):\n    pass\n",
      tests: [
        { call: "initials(\"ada lovelace\")", expected: "\"A.L\"" },
        { call: "initials(\"Grace Brewster Hopper\")", expected: "\"G.B.H\"" },
        { call: "initials(\"solo\")", expected: "\"S\"", hidden: true },
      ],
      tutorial: { en: "`.split()` cuts a sentence into a list of words. Take the first letter of each, then join them with \".\"." },
      editorial: { en: "    def initials(full_name):\n        letters = []\n        for word in full_name.split():\n            letters.append(word[0].upper())\n        return \".\".join(letters)\n\n\".\".join(list) glues a list of pieces together with a dot between each." },
      explanation: { en: "split and join are opposites, and between them they handle most of the text work you will ever do." },
    },
    {
      id: "pp-c-6-hard",
      lessonId: "pp-6",
      order: 17,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "Same backwards", fr: "Pareil \u00e0 l'envers" },
      prompt: { en: "Write `is_palindrome` that RETURNS True when a word reads the same backwards, ignoring capitals. \"Level\" is True, \"robot\" is False.", fr: "\u00c9cris `is_palindrome` qui RENVOIE True quand un mot se lit pareil \u00e0 l'envers, sans tenir compte des majuscules. \"Level\" donne True, \"robot\" donne False." },
      options: [],
      correctIndex: 0,
      starterCode: "def is_palindrome(word):\n    pass\n",
      tests: [
        { call: "is_palindrome(\"Level\")", expected: "True" },
        { call: "is_palindrome(\"robot\")", expected: "False" },
        { call: "is_palindrome(\"aa\")", expected: "True" },
        { call: "is_palindrome(\"\")", expected: "True", hidden: true },
      ],
      tutorial: { en: "Lower it first so capitals stop mattering. `word[::-1]` gives the word backwards." },
      editorial: { en: "    def is_palindrome(word):\n        word = word.lower()\n        return word == word[::-1]\n\n[::-1] is a slice with a step of -1, which walks the string from the end." },
      explanation: { en: "Comparing a thing to a changed copy of itself is a neat trick that shows up in a lot of puzzles." },
    },
    {
      id: "pp-c-7-easy",
      lessonId: "pp-7",
      order: 18,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "How many", fr: "Combien" },
      prompt: { en: "Write `how_many` that takes a list and RETURNS how many things are in it.", fr: "\u00c9cris `how_many` qui prend une liste et RENVOIE combien de choses elle contient." },
      options: [],
      correctIndex: 0,
      starterCode: "def how_many(items):\n    pass\n",
      tests: [
        { call: "how_many([\"a\", \"b\", \"c\"])", expected: "3" },
        { call: "how_many([])", expected: "0" },
        { call: "how_many([1])", expected: "1", hidden: true },
      ],
      tutorial: { en: "`len(items)` already answers this." },
      editorial: { en: "    def how_many(items):\n        return len(items)\n\nlen works on lists and on strings, and means the same thing in both: how many." },
      explanation: { en: "Python often has the answer built in. Looking before writing a loop is a real skill." },
    },
    {
      id: "pp-c-7-medium",
      lessonId: "pp-7",
      order: 19,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Average", fr: "La moyenne" },
      prompt: { en: "Write `average` that takes a list of numbers and RETURNS their average, rounded to 2 decimal places. An empty list gives 0.", fr: "\u00c9cris `average` qui prend une liste de nombres et RENVOIE leur moyenne, arrondie \u00e0 2 d\u00e9cimales. Une liste vide donne 0." },
      options: [],
      correctIndex: 0,
      starterCode: "def average(numbers):\n    pass\n",
      tests: [
        { call: "average([10, 20, 30])", expected: "20.0" },
        { call: "average([1, 2])", expected: "1.5" },
        { call: "average([])", expected: "0" },
        { call: "average([1, 2, 2])", expected: "1.67", hidden: true },
      ],
      tutorial: { en: "sum(numbers) / len(numbers), then round(x, 2). Check for the empty list first, or you divide by zero." },
      editorial: { en: "    def average(numbers):\n        if not numbers:\n            return 0\n        return round(sum(numbers) / len(numbers), 2)\n\n`not numbers` is True for an empty list. It reads better than len(numbers) == 0." },
      explanation: { en: "sum, len, and a guard against empty. That combination is most of what data work is." },
    },
    {
      id: "pp-c-7-hard",
      lessonId: "pp-7",
      order: 20,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "The longest word", fr: "Le mot le plus long" },
      prompt: { en: "Write `longest` that takes a list of words and RETURNS the longest one. If two are the same length, return the one that comes first. An empty list gives \"\".", fr: "\u00c9cris `longest` qui prend une liste de mots et RENVOIE le plus long. Si deux ont la m\u00eame longueur, renvoie le premier. Une liste vide donne \"\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def longest(words):\n    pass\n",
      tests: [
        { call: "longest([\"hi\", \"robot\", \"ai\"])", expected: "\"robot\"" },
        { call: "longest([\"aa\", \"bb\"])", expected: "\"aa\"" },
        { call: "longest([])", expected: "\"\"" },
        { call: "longest([\"one\"])", expected: "\"one\"", hidden: true },
      ],
      tutorial: { en: "Keep a `best` variable, start it at \"\", and replace it whenever you find something strictly longer. Strictly longer is what keeps the first of a tie." },
      editorial: { en: "    def longest(words):\n        best = \"\"\n        for word in words:\n            if len(word) > len(best):\n                best = word\n        return best\n\nUsing > and not >= is the whole reason a tie keeps the earlier word." },
      explanation: { en: "\"Keep the best so far\" is a pattern you will use for the rest of your life as a programmer." },
    },
    {
      id: "pp-c-8-easy",
      lessonId: "pp-8",
      order: 21,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "Read the battery", fr: "Lire la batterie" },
      prompt: { en: "Write `get_level` that takes a dictionary and RETURNS its \"level\" value, or 0 if there is no level key.", fr: "\u00c9cris `get_level` qui prend un dictionnaire et RENVOIE sa valeur \"level\", ou 0 s'il n'y a pas de cl\u00e9 level." },
      options: [],
      correctIndex: 0,
      starterCode: "def get_level(battery):\n    pass\n",
      tests: [
        { call: "get_level({\"level\": 82})", expected: "82" },
        { call: "get_level({})", expected: "0" },
        { call: "get_level({\"charging\": True})", expected: "0", hidden: true },
      ],
      tutorial: { en: "`.get(\"level\", 0)` looks up the key and hands back 0 instead of crashing when it is missing." },
      editorial: { en: "    def get_level(battery):\n        return battery.get(\"level\", 0)\n\nbattery[\"level\"] would crash on a dictionary that has no level." },
      explanation: { en: ".get with a fallback is how you survive data you did not create yourself." },
    },
    {
      id: "pp-c-8-medium",
      lessonId: "pp-8",
      order: 22,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "Count them", fr: "Compte-les" },
      prompt: { en: "Write `tally` that takes a list and RETURNS a dictionary counting how many times each thing appears.", fr: "\u00c9cris `tally` qui prend une liste et RENVOIE un dictionnaire comptant combien de fois chaque chose appara\u00eet." },
      options: [],
      correctIndex: 0,
      starterCode: "def tally(values):\n    pass\n",
      tests: [
        { call: "tally([\"a\", \"b\", \"a\"])", expected: "{\"a\": 2, \"b\": 1}" },
        { call: "tally([])", expected: "{}" },
        { call: "tally([1, 1, 1])", expected: "{1: 3}", hidden: true },
      ],
      tutorial: { en: "Start with an empty dictionary. For each value: take what is already counted (or 0), add one, put it back." },
      editorial: { en: "    def tally(values):\n        counts = {}\n        for value in values:\n            counts[value] = counts.get(value, 0) + 1\n        return counts\n\nThat middle line is the whole trick, and it is worth learning by heart." },
      explanation: { en: "This exact three-line pattern counts words in a book, colours in an image, or votes in an election." },
    },
    {
      id: "pp-c-8-hard",
      lessonId: "pp-8",
      order: 23,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "The most common", fr: "Le plus fr\u00e9quent" },
      prompt: { en: "Write `most_common` that takes a list and RETURNS the thing that appears most often. If the list is empty, return None.", fr: "\u00c9cris `most_common` qui prend une liste et RENVOIE la chose qui appara\u00eet le plus souvent. Si la liste est vide, renvoie None." },
      options: [],
      correctIndex: 0,
      starterCode: "def most_common(values):\n    pass\n",
      tests: [
        { call: "most_common([\"a\", \"b\", \"a\"])", expected: "\"a\"" },
        { call: "most_common([])", expected: "None" },
        { call: "most_common([7])", expected: "7" },
        { call: "most_common([\"x\", \"y\", \"y\", \"x\", \"y\"])", expected: "\"y\"", hidden: true },
      ],
      tutorial: { en: "Count them first, exactly as in the medium one. Then walk the counts keeping the best so far -- the same pattern as the longest word." },
      editorial: { en: "    def most_common(values):\n        counts = {}\n        for value in values:\n            counts[value] = counts.get(value, 0) + 1\n\n        best = None\n        best_count = 0\n        for value, count in counts.items():\n            if count > best_count:\n                best = value\n                best_count = count\n        return best\n\nTwo patterns you already know, one after the other. Most real programs are exactly this." },
      explanation: { en: "Notice you learned nothing new here -- you combined two things you already had. That is what programming turns into." },
    },
    {
      id: "pp-c-9-easy",
      lessonId: "pp-9",
      order: 24,
      status: "published",
      difficulty: "easy",
      kind: "code",
      title: { en: "The check-up", fr: "Le bilan" },
      prompt: { en: "Write `check_up` that takes battery and distance and RETURNS \"charge\" when the battery is under 20, \"stop\" when the distance is under 20, and \"go\" otherwise. Check the battery first.", fr: "\u00c9cris `check_up` qui prend batterie et distance et RENVOIE \"charge\" si la batterie est sous 20, \"stop\" si la distance est sous 20, et \"go\" sinon. V\u00e9rifie la batterie en premier." },
      options: [],
      correctIndex: 0,
      starterCode: "def check_up(battery, distance):\n    pass\n",
      tests: [
        { call: "check_up(45, 12)", expected: "\"stop\"" },
        { call: "check_up(15, 50)", expected: "\"charge\"" },
        { call: "check_up(80, 40)", expected: "\"go\"" },
        { call: "check_up(10, 10)", expected: "\"charge\"", hidden: true },
      ],
      tutorial: { en: "if / elif / else, in the order the question gives them. The hidden test has BOTH problems at once -- battery wins because it is checked first." },
      editorial: { en: "    def check_up(battery, distance):\n        if battery < 20:\n            return \"charge\"\n        elif distance < 20:\n            return \"stop\"\n        return \"go\"" },
      explanation: { en: "When two things are wrong at once, the order of your ifs decides which one the robot acts on. That is a design decision, not an accident." },
    },
    {
      id: "pp-c-9-medium",
      lessonId: "pp-9",
      order: 25,
      status: "published",
      difficulty: "medium",
      kind: "code",
      title: { en: "The sensor report", fr: "Le rapport des capteurs" },
      prompt: { en: "Write `report` that takes a list of distances and RETURNS a dictionary with keys \"count\", \"closest\" and \"furthest\". An empty list gives all three as 0.", fr: "\u00c9cris `report` qui prend une liste de distances et RENVOIE un dictionnaire avec les cl\u00e9s \"count\", \"closest\" et \"furthest\". Une liste vide donne 0 partout." },
      options: [],
      correctIndex: 0,
      starterCode: "def report(readings):\n    pass\n",
      tests: [
        { call: "report([12, 40, 7])", expected: "{\"count\": 3, \"closest\": 7, \"furthest\": 40}" },
        { call: "report([])", expected: "{\"count\": 0, \"closest\": 0, \"furthest\": 0}" },
        { call: "report([5])", expected: "{\"count\": 1, \"closest\": 5, \"furthest\": 5}", hidden: true },
      ],
      tutorial: { en: "len, min and max do all three. Guard the empty list first -- min of nothing crashes." },
      editorial: { en: "    def report(readings):\n        if not readings:\n            return {\"count\": 0, \"closest\": 0, \"furthest\": 0}\n        return {\n            \"count\": len(readings),\n            \"closest\": min(readings),\n            \"furthest\": max(readings),\n        }" },
      explanation: { en: "Returning a dictionary is how one function hands back several answers at once, each with a name." },
    },
    {
      id: "pp-c-9-hard",
      lessonId: "pp-9",
      order: 26,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "The mission", fr: "La mission" },
      prompt: { en: "Write `mission` that takes a list of distances and RETURNS a list of actions, one per reading: \"stop\" when under 20, otherwise \"turn\" if the PREVIOUS action was \"stop\", otherwise \"go\".", fr: "\u00c9cris `mission` qui prend une liste de distances et RENVOIE une liste d'actions, une par mesure : \"stop\" si sous 20, sinon \"turn\" si l'action PR\u00c9C\u00c9DENTE \u00e9tait \"stop\", sinon \"go\"." },
      options: [],
      correctIndex: 0,
      starterCode: "def mission(readings):\n    actions = []\n    previous = None\n    # Decide each action, then remember it for the next one.\n    return actions\n",
      tests: [
        { call: "mission([50, 10, 40])", expected: "[\"go\", \"stop\", \"turn\"]" },
        { call: "mission([10, 10])", expected: "[\"stop\", \"stop\"]" },
        { call: "mission([])", expected: "[]" },
        { call: "mission([30, 15, 30, 30])", expected: "[\"go\", \"stop\", \"turn\", \"go\"]", hidden: true },
      ],
      tutorial: { en: "You cannot answer a reading on its own -- you need what you decided last time. Keep a `previous` variable and update it at the end of every turn of the loop." },
      editorial: { en: "    def mission(readings):\n        actions = []\n        previous = None\n        for reading in readings:\n            if reading < 20:\n                action = \"stop\"\n            elif previous == \"stop\":\n                action = \"turn\"\n            else:\n                action = \"go\"\n            actions.append(action)\n            previous = action\n        return actions\n\nThe order inside the loop matters: decide, record, THEN remember." },
      explanation: { en: "This is the first one you cannot solve by looking at each item on its own. A robot that remembers what it just did is running a control loop -- which is the whole of the next track." },
    },
      {
      id: "pp-c-final",
      lessonId: "pp-9",
      isExam: true,
      order: 27,
      status: "published",
      difficulty: "hard",
      kind: "code",
      title: { en: "Final project — mission control", fr: "Projet final — contrôle de mission" },
      prompt: { en: "The final exam. One robot, four jobs, and everything the nine chapters taught.\n\n1. `battery_state(level)` \u2014 \"charge\" under 20, \"low\" under 50, \"ok\" otherwise.\n2. `close_readings(readings)` \u2014 a list of only the readings under 20, in the same order.\n3. `tally_actions(actions)` \u2014 how many times each action appears, as a dictionary.\n4. `summary(name, readings)` \u2014 \"Axi took 3 readings, closest 7 cm.\" An empty list gives \"Axi took 0 readings.\"\n\nDo them one at a time. Each one you finish turns more of the tests green, so you can see how far you have got.", fr: "L'examen final. Un robot, quatre t\u00e2ches, et tout ce que les neuf chapitres ont appris.\n\n1. `battery_state(level)` \u2014 \"charge\" sous 20, \"low\" sous 50, \"ok\" sinon.\n2. `close_readings(readings)` \u2014 une liste des seules mesures sous 20, dans le m\u00eame ordre.\n3. `tally_actions(actions)` \u2014 combien de fois chaque action appara\u00eet, sous forme de dictionnaire.\n4. `summary(name, readings)` \u2014 \"Axi took 3 readings, closest 7 cm.\" Une liste vide donne \"Axi took 0 readings.\"\n\nFais-les une par une. Chaque t\u00e2che finie fait passer d'autres tests au vert, donc tu vois o\u00f9 tu en es." },
      options: [],
      correctIndex: 0,
      starterCode: "# Mission control.\n# Four small jobs. Do them one at a time -- each is worth marks on its own.\n\ndef battery_state(level):\n    # \"charge\" under 20, \"low\" under 50, otherwise \"ok\".\n    pass\n\n\ndef close_readings(readings):\n    # A list of only the readings under 20, in the same order.\n    pass\n\n\ndef tally_actions(actions):\n    # How many times each action appears, as a dictionary.\n    pass\n\n\ndef summary(name, readings):\n    # \"Axi took 3 readings, closest 7 cm.\"\n    # An empty list gives \"Axi took 0 readings.\"\n    pass\n",
      tests: [
        { call: "battery_state(10)", expected: "\"charge\"" },
        { call: "battery_state(35)", expected: "\"low\"" },
        { call: "battery_state(80)", expected: "\"ok\"" },
        { call: "battery_state(20)", expected: "\"low\"", hidden: true },
        { call: "battery_state(50)", expected: "\"ok\"", hidden: true },
        { call: "close_readings([30, 12, 40, 7])", expected: "[12, 7]" },
        { call: "close_readings([50, 60])", expected: "[]" },
        { call: "close_readings([])", expected: "[]", hidden: true },
        { call: "tally_actions([\"go\", \"stop\", \"go\"])", expected: "{\"go\": 2, \"stop\": 1}" },
        { call: "tally_actions([])", expected: "{}", hidden: true },
        { call: "summary(\"Axi\", [12, 40, 7])", expected: "\"Axi took 3 readings, closest 7 cm.\"" },
        { call: "summary(\"Robo\", [])", expected: "\"Robo took 0 readings.\"" },
        { call: "summary(\"X\", [5])", expected: "\"X took 1 readings, closest 5 cm.\"", hidden: true },
      ],
      tutorial: { en: "Nothing here is new. Each job is one thing you have already done:\n\n1. if / elif / else, biggest first \u2014 chapter 3.\n2. an empty list, a for loop, append when the condition holds \u2014 chapters 4 and 7.\n3. counts[x] = counts.get(x, 0) + 1 \u2014 chapter 8.\n4. an f-string, len and min, with a guard for the empty list \u2014 chapters 6 and 7.\n\nWrite one, run it, watch its tests turn green, then start the next. Do not try to write all four before running anything." },
      editorial: { en: "    def battery_state(level):\n        if level < 20:\n            return \"charge\"\n        elif level < 50:\n            return \"low\"\n        return \"ok\"\n\n    def close_readings(readings):\n        out = []\n        for r in readings:\n            if r < 20:\n                out.append(r)\n        return out\n\n    def tally_actions(actions):\n        counts = {}\n        for a in actions:\n            counts[a] = counts.get(a, 0) + 1\n        return counts\n\n    def summary(name, readings):\n        if not readings:\n            return f\"{name} took 0 readings.\"\n        return f\"{name} took {len(readings)} readings, closest {min(readings)} cm.\"\n\nFour functions, none longer than five lines. That is what nine chapters buys you." },
      explanation: { en: "That is the whole Python track, working together in one program. The certificate is yours." },
    },
],
};
